/**
 * Type-V Virtual Machine
 * Author: praisethemoon
 * instructions.h: VM Instructions
 * VM instructions headers are defined here.
 */

#ifndef TYPE_V_INSTRUCTIONS_H
#define TYPE_V_INSTRUCTIONS_H

#include "../core.h"
#include "./opcodes.h"

#define VM_INSTRUCTION(instruction) void instruction(TypeV_Core *core);

VM_INSTRUCTION(mv_reg_reg)
VM_INSTRUCTION(mv_reg_i)
VM_INSTRUCTION(mv_reg_const_8)
VM_INSTRUCTION(mv_reg_const_16)
VM_INSTRUCTION(mv_reg_const_32)
VM_INSTRUCTION(mv_reg_const_64)
VM_INSTRUCTION(mv_reg_const_ptr)
VM_INSTRUCTION(mv_reg_mem)
VM_INSTRUCTION(mv_mem_reg)

VM_INSTRUCTION(mv_reg_local_8)
VM_INSTRUCTION(mv_reg_local_16)
VM_INSTRUCTION(mv_reg_local_32)
VM_INSTRUCTION(mv_reg_local_64)
VM_INSTRUCTION(mv_reg_local_ptr)

VM_INSTRUCTION(mv_local_reg_8)
VM_INSTRUCTION(mv_local_reg_16)
VM_INSTRUCTION(mv_local_reg_32)
VM_INSTRUCTION(mv_local_reg_64)
VM_INSTRUCTION(mv_local_reg_ptr)

VM_INSTRUCTION(mv_global_reg_8)
VM_INSTRUCTION(mv_global_reg_16)
VM_INSTRUCTION(mv_global_reg_32)
VM_INSTRUCTION(mv_global_reg_64)
VM_INSTRUCTION(mv_global_reg_ptr)

VM_INSTRUCTION(mv_reg_global_8)
VM_INSTRUCTION(mv_reg_global_16)
VM_INSTRUCTION(mv_reg_global_32)
VM_INSTRUCTION(mv_reg_global_64)
VM_INSTRUCTION(mv_reg_global_ptr)

VM_INSTRUCTION(mv_reg_arg_8)
VM_INSTRUCTION(mv_reg_arg_16)
VM_INSTRUCTION(mv_reg_arg_32)
VM_INSTRUCTION(mv_reg_arg_64)
VM_INSTRUCTION(mv_reg_arg_ptr)

VM_INSTRUCTION(mv_arg_reg_8)
VM_INSTRUCTION(mv_arg_reg_16)
VM_INSTRUCTION(mv_arg_reg_32)
VM_INSTRUCTION(mv_arg_reg_64)
VM_INSTRUCTION(mv_arg_reg_ptr)

VM_INSTRUCTION(s_alloc)
VM_INSTRUCTION(s_alloc_shadow)
VM_INSTRUCTION(s_set_offset)

VM_INSTRUCTION(s_loadf)

VM_INSTRUCTION(s_storef_const_8)
VM_INSTRUCTION(s_storef_const_16)
VM_INSTRUCTION(s_storef_const_32)
VM_INSTRUCTION(s_storef_const_64)
VM_INSTRUCTION(s_storef_const_ptr)

VM_INSTRUCTION(s_storef_reg)

VM_INSTRUCTION(c_allocf)
VM_INSTRUCTION(c_allocm)
VM_INSTRUCTION(c_storem)
VM_INSTRUCTION(c_loadm)

VM_INSTRUCTION(c_storef_reg)

VM_INSTRUCTION(c_storef_const_8)
VM_INSTRUCTION(c_storef_const_16)
VM_INSTRUCTION(c_storef_const_32)
VM_INSTRUCTION(c_storef_const_64)
VM_INSTRUCTION(c_storef_const_ptr)

VM_INSTRUCTION(c_loadf)

VM_INSTRUCTION(i_alloc)
VM_INSTRUCTION(i_set_offset)
VM_INSTRUCTION(i_loadm)

VM_INSTRUCTION(a_alloc)
VM_INSTRUCTION(a_extend)

VM_INSTRUCTION(a_storef_reg)
VM_INSTRUCTION(a_storef_const_8)
VM_INSTRUCTION(a_storef_const_16)
VM_INSTRUCTION(a_storef_const_32)
VM_INSTRUCTION(a_storef_const_64)
VM_INSTRUCTION(a_storef_const_ptr)

VM_INSTRUCTION(a_loadf)

VM_INSTRUCTION(push)
VM_INSTRUCTION(push_const)
VM_INSTRUCTION(pop)

VM_INSTRUCTION(frame_init_args)
VM_INSTRUCTION(frame_init_locals)
VM_INSTRUCTION(frame_rm)
VM_INSTRUCTION(frame_precall)

VM_INSTRUCTION(fn_main)
VM_INSTRUCTION(fn_ret)
VM_INSTRUCTION(fn_call)
VM_INSTRUCTION(fn_calli)

VM_INSTRUCTION(cast_i8_u8)
VM_INSTRUCTION(cast_u8_i8)
VM_INSTRUCTION(cast_i16_u16)
VM_INSTRUCTION(cast_u16_i16)
VM_INSTRUCTION(cast_i32_u32)
VM_INSTRUCTION(cast_u32_i32)
VM_INSTRUCTION(cast_i64_u64)
VM_INSTRUCTION(cast_u64_i64)
VM_INSTRUCTION(cast_i32_f32)
VM_INSTRUCTION(cast_f32_i32)
VM_INSTRUCTION(cast_i64_f64)
VM_INSTRUCTION(cast_f64_i64)

VM_INSTRUCTION(upcast_i8_i16)
VM_INSTRUCTION(upcast_u8_u16)
VM_INSTRUCTION(upcast_i16_i32)
VM_INSTRUCTION(upcast_u16_u32)
VM_INSTRUCTION(upcast_i32_i64)
VM_INSTRUCTION(upcast_u32_u64)
VM_INSTRUCTION(upcast_f32_f64)

VM_INSTRUCTION(dcast_i16_i8)
VM_INSTRUCTION(dcast_u16_u8)
VM_INSTRUCTION(dcast_i32_i16)
VM_INSTRUCTION(dcast_u32_u16)
VM_INSTRUCTION(dcast_i64_i32)
VM_INSTRUCTION(dcast_u64_u32)
VM_INSTRUCTION(dcast_f64_f32)

VM_INSTRUCTION(add_i8)
VM_INSTRUCTION(add_u8)
VM_INSTRUCTION(add_i16)
VM_INSTRUCTION(add_u16)
VM_INSTRUCTION(add_i32)
VM_INSTRUCTION(add_u32)
VM_INSTRUCTION(add_i64)
VM_INSTRUCTION(add_u64)
VM_INSTRUCTION(add_f32)
VM_INSTRUCTION(add_f64)
VM_INSTRUCTION(add_ptr_u8)
VM_INSTRUCTION(add_ptr_u16)
VM_INSTRUCTION(add_ptr_u32)
VM_INSTRUCTION(add_ptr_u64)

VM_INSTRUCTION(sub_i8)
VM_INSTRUCTION(sub_u8)
VM_INSTRUCTION(sub_i16)
VM_INSTRUCTION(sub_u16)
VM_INSTRUCTION(sub_i32)
VM_INSTRUCTION(sub_u32)
VM_INSTRUCTION(sub_i64)
VM_INSTRUCTION(sub_u64)
VM_INSTRUCTION(sub_f32)
VM_INSTRUCTION(sub_f64)
VM_INSTRUCTION(sub_ptr_u8)
VM_INSTRUCTION(sub_ptr_u16)
VM_INSTRUCTION(sub_ptr_u32)
VM_INSTRUCTION(sub_ptr_u64)

VM_INSTRUCTION(mul_i8)
VM_INSTRUCTION(mul_u8)
VM_INSTRUCTION(mul_i16)
VM_INSTRUCTION(mul_u16)
VM_INSTRUCTION(mul_i32)
VM_INSTRUCTION(mul_u32)
VM_INSTRUCTION(mul_i64)
VM_INSTRUCTION(mul_u64)
VM_INSTRUCTION(mul_f32)
VM_INSTRUCTION(mul_f64)

VM_INSTRUCTION(div_i8)
VM_INSTRUCTION(div_u8)
VM_INSTRUCTION(div_i16)
VM_INSTRUCTION(div_u16)
VM_INSTRUCTION(div_i32)
VM_INSTRUCTION(div_u32)
VM_INSTRUCTION(div_i64)
VM_INSTRUCTION(div_u64)
VM_INSTRUCTION(div_f32)
VM_INSTRUCTION(div_f64)

VM_INSTRUCTION(mod_i8)
VM_INSTRUCTION(mod_u8)
VM_INSTRUCTION(mod_i16)
VM_INSTRUCTION(mod_u16)
VM_INSTRUCTION(mod_i32)
VM_INSTRUCTION(mod_u32)
VM_INSTRUCTION(mod_i64)
VM_INSTRUCTION(mod_u64)

VM_INSTRUCTION(lshift_i8)
VM_INSTRUCTION(lshift_u8)
VM_INSTRUCTION(lshift_i16)
VM_INSTRUCTION(lshift_u16)
VM_INSTRUCTION(lshift_i32)
VM_INSTRUCTION(lshift_u32)
VM_INSTRUCTION(lshift_i64)
VM_INSTRUCTION(lshift_u64)

VM_INSTRUCTION(rshift_i8)
VM_INSTRUCTION(rshift_u8)
VM_INSTRUCTION(rshift_i16)
VM_INSTRUCTION(rshift_u16)
VM_INSTRUCTION(rshift_i32)
VM_INSTRUCTION(rshift_u32)
VM_INSTRUCTION(rshift_i64)
VM_INSTRUCTION(rshift_u64)

VM_INSTRUCTION(cmp_i8)
VM_INSTRUCTION(cmp_u8)
VM_INSTRUCTION(cmp_i16)
VM_INSTRUCTION(cmp_u16)
VM_INSTRUCTION(cmp_i32)
VM_INSTRUCTION(cmp_u32)
VM_INSTRUCTION(cmp_i64)
VM_INSTRUCTION(cmp_u64)
VM_INSTRUCTION(cmp_f32)
VM_INSTRUCTION(cmp_f64)
VM_INSTRUCTION(cmp_ptr)

VM_INSTRUCTION(band_8)
VM_INSTRUCTION(band_16)
VM_INSTRUCTION(band_32)
VM_INSTRUCTION(band_64)

VM_INSTRUCTION(bor_8)
VM_INSTRUCTION(bor_16)
VM_INSTRUCTION(bor_32)
VM_INSTRUCTION(bor_64)

VM_INSTRUCTION(bxor_8)
VM_INSTRUCTION(bxor_16)
VM_INSTRUCTION(bxor_32)
VM_INSTRUCTION(bxor_64)

VM_INSTRUCTION(bnot_8)
VM_INSTRUCTION(bnot_16)
VM_INSTRUCTION(bnot_32)
VM_INSTRUCTION(bnot_64)

VM_INSTRUCTION(and)
VM_INSTRUCTION(or)
VM_INSTRUCTION(not)

VM_INSTRUCTION(jmp)
VM_INSTRUCTION(jmp_e)
VM_INSTRUCTION(jmp_ne)
VM_INSTRUCTION(jmp_g)
VM_INSTRUCTION(jmp_ge)
VM_INSTRUCTION(jmp_l)
VM_INSTRUCTION(jmp_le)

VM_INSTRUCTION(ld_ffi)
VM_INSTRUCTION(call_ffi)
VM_INSTRUCTION(close_ffi)

VM_INSTRUCTION(p_alloc)
VM_INSTRUCTION(p_dequeue)
VM_INSTRUCTION(p_queue_size)
VM_INSTRUCTION(p_emit)
VM_INSTRUCTION(p_wait_queue)
VM_INSTRUCTION(p_send_sig)
VM_INSTRUCTION(p_id)
VM_INSTRUCTION(p_cid)
VM_INSTRUCTION(p_state)

VM_INSTRUCTION(promise_alloc)
VM_INSTRUCTION(promise_resolve)
VM_INSTRUCTION(promise_await)
VM_INSTRUCTION(promise_data)

VM_INSTRUCTION(debug_reg)
VM_INSTRUCTION(halt)

VM_INSTRUCTION(vm_health)

#endif //TYPE_V_INSTRUCTIONS_H
